#! /usr/bin/env python
from PIL import Image, ImageDraw

image = Image.new('RGB', (1920,1080), 'white')
draw = ImageDraw.Draw(image)
# Body
draw.rectangle([(1000, 420), (1050,660)], fill='black')

# Head
draw.rectangle([(940, 380), (1050, 420)], fill='black')
draw.pieslice([(940, 360), (980, 400)], start=180, end=270, fill='black')
draw.pieslice([(1010, 360), (1050, 400)], start=270, end=360, fill='black')
draw.rectangle([(960,360), (1030, 380)], fill='black')

# Eye
draw.pieslice([(965,375), (985, 395)], start=0, end=360, fill='white')

# Mouth
draw.chord([(920, 370), (1005, 440)], start=20, end=120, fill='black')

# TODO: Microphone

# TODO: Tail? Or stage (with screen/projector?)? Or tail circled around to make a circular 'viewing window'?
image.show()
